USE codeup_test_db;

DROP TABLE IF EXISTS albums;
CREATE TABLE albums(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	artist VARCHAR(200) NOT NULL,
	album_name VARCHAR(255) NOT NULL,
	release_date YEAR(4) NOT NULL,
	sales FLOAT(5,2) NOT NULL,
	genre VARCHAR(100) NOT NULL,
	PRIMARY KEY (id) 			
);

